trigger: none
variables:
  ADO_PAT: $(ADO_PAT)     # Secure variable
  ADO_ORG: 'your-org-name'

pool:
  name: Default

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: 'scripts/add-users-from-csv.ps1'
    displayName: 'Add Users to Azure DevOps'
